spring:
  application:
    name: modzuul-gateway
server:
  port: 9000
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    fetchRegistry: true
    registerWithEureka: true
  instance:
    preferIpAddress: true